### ISSUE TITLE
Running the Acceptance tests requires some undocumented Docker setup

### ISSUE THREAD

**Issue by cgfrost** [spring-cloud-samples/brewery#15]
Having cloned the repo and built it with `gradlew clean build` I'm unable to run the acceptance tests. I have installed `docker` and `docker-compose` for the first time but that isn't enough to get the tests to run. Fails with 

```
ERROR: Couldn't connect to Docker daemon - you might need to run docker-machine start default.
```

**Comment by marcingrzejszczak** [comment]
Are you sure you just ran `./gradlew clean build` ? Cause that doesn't doesn't run any Docker stuff.

As far as the 

```
ERROR: Couldn't connect to Docker daemon - you might need to run docker-machine start default.
``` 

is concerned - it's not the case of brewery. You have wrong Docker setup so `docker-compose` can't get executed.

**Comment by cgfrost** [comment]
Sorry, that wasn't clear. I got the error after running `./runAcceptanceTests.sh`.

What is wrong with my Docker setup, I've not used it before so I don't know what I should be doing. I'm just following the instructions in the readme.

**Comment by marcingrzejszczak** [comment]
Maybe let's go to gitter of spring-cloud - https://gitter.im/spring-cloud/spring-cloud ?

**Comment by marcingrzejszczak** [comment]
ok you didn't go there... it's not undocumented usage. I guess you're on a mac - then you have to set up your local instance of docker-machine. Please check articles like:

* https://github.com/docker/compose/issues/2180
* https://github.com/docker/compose/issues/2495
* http://stackoverflow.com/questions/29101043/cant-connect-to-docker-from-docker-compose
