### ISSUE TITLE
What is http://brewery-presenting.${PCF_DOMAIN} / broken link?

### ISSUE THREAD

**Issue by paulvi** [spring-cloud-samples/brewery#22]
What is http://brewery-presenting.${PCF_DOMAIN} in README? broken link?

**Comment by marcingrzejszczak** [comment]
`PCF_DOMAIN` is the domain set to your CF installation. If you deploy to Pivotal Web Services it will default to `cfapps.io` (so the link for PWS will be http://brewery-presenting.cfapps.io
